# Generated by Django 3.0.5 on 2020-05-03 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 14, 21, 24, 432530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 14, 21, 24, 433531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 14, 21, 24, 432530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Post',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
