# Generated by Django 3.0.5 on 2020-05-05 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200503_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 9, 32, 18, 780254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 9, 32, 18, 780254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 9, 32, 18, 780254, tzinfo=utc)),
        ),
    ]
